import { Injectable } from '@angular/core';

Injectable();
export class Dictio {

    public static keys = {

        de: {
            Delete: 'Löschen',
            'Basic search': 'Grundlagensuche',
            Search: 'Suche',
            Reset: 'Zurücksetzen',
            New: 'Neu',
            Details: 'Einzelheiten',
            Calculate: 'Berechnen',
            'Update Overall': 'Aktualisierung insgesamt',
            Forecast: 'Prognose',
            'Forecast type': 'Prognosetyp',
            Cancel: 'Annullieren',
            'Demand Planning': 'Bedarfsplanung',
            Modified: 'Geändert',
            'Valid from': 'Gültig von',
            'Valid to': 'Gültig bis',
            'Calc?': 'Berechnend?',
            Calc: 'Berechnet',
            'Used?': 'Benutzt',
            'Generate Tender': 'Generieren Tender',
            'Tender name': 'Tender name',
            'Choose profile': 'Wählen Profil',
            'Choose forecast': 'Wählen Prognose',
            'Tender period start': 'Tender period start',
            'Tender period from': 'Tender period von',
            'Contract period start': 'Kontrakt period start ',
            'Contract period from': 'Kontrakt period von',
            Generate: 'Generieren',
            Close: 'Schließen',
            'Fuel Tender': 'Brennstoff-Tender',
            Name: 'Name',
            Code: 'Code',
            Buyer: 'Käufer',
            Location: 'Stelle',
            Status: 'Status',
            'Contract from': 'Kontrakt von',
            'Contract until': 'Kontrakt bis',
            Customers: 'Kunden',
            'Int rate': 'Zinsrate',
            Type: 'typ',
            Unit: 'Einheit',
            'Unit ref': 'Einheit Referenz',
            Currency: 'Währung',
            'Ref quot': 'Referenzzitat',
            Publish: 'Publizieren',
            'Choose format': 'Format wählen',
            'Choose layout': 'Layout wählen',
            'Export columns': 'Export Spalten',
            'Visible columns': 'Sichtbare Säulen',
            'All columns': 'Alle Spalten',
            Export: 'Exportieren',
            'Go to account settings': 'Gehen zu Kontoeinstellungen',
            'Open reports': 'Offene Berichte',
            'Change color scheme': 'Farbschema ändern',
            'Change language': 'Sprache ändern',
            'Leave application...': 'Verlassen Anwendung...',
            'Filter navigation...': 'Filter-Navigation...',
            Contracts: 'Kontrakte',
            Preview: 'Vorschau',
            'Add note': 'Notiz hinzufügen',
            Notes: 'Notizen',
            Class: 'Klasse',
            Content: 'Inhalt',
            Url: 'Url',
            'added a': 'Hinzugefügt a',
            'note on': 'Hinweis auf',
            Attachements: 'Anhänge',
            'Document type': 'Dokumententyp',
            'Is document obsolete': 'Ist Dokument obsolet?',
            Description: 'Beschreibung',
            Choose: 'Wählen',
            'Upload file': 'Upload-Datei',
            Save: 'Speichern'
        },
        fr: {
            Delete: 'Supprimer',
            'Basic search': 'Recherche de base',
            Search: 'Rechercher',
            Reset: 'Réinitialiser',
            New: 'Nouveau',
            Details: 'Détails',
            Calculate: 'Calculer',
            'Update Overall': 'Mise à jour globale',
            Forecast: 'Prévision',
            'Forecast type': 'Type de prévision',
            Cancel: 'Annuler',
            'Demand Planning': 'Planification de la demandde',
            Modified: 'Modifié',
            'Valid from': 'Valide de',
            'Valid to': 'Valide jusqu\'à',
            'Calc?': 'Calc?',
            Calc: 'Calc',
            'Used?': 'Utilisé',
            'Generate Tender': 'Générer l\'Offre',
            'Tender name': 'Nom de l\'Offre',
            'Choose profile': 'Choisir le profil',
            'Choose forecast': 'Choisir la prévision',
            'Tender period start': 'Début de période d\'offre',
            'Tender period from': 'Période d\'offre depuis',
            'Contract period start': 'Début de période contractuelle',
            'Contract period from': 'Début du contrat',
            Generate: 'Générer',
            Close: 'Fermer',
            'Fuel Tender': 'Offre de combustible',
            Name: 'Nom',
            Code: 'Code',
            Buyer: 'Acheteur',
            Location: 'Lieu',
            Status: 'Statut',
            'Contract from': 'Contract de',
            'Contract until': 'Contract à',
            Customers: 'Clients',
            'Int rate': 'Taux d\'intérêt',
            Unit: 'Unité',
            'Unit ref': 'Référence d\'unité',
            Currency: 'Monnais',
            'Ref quot': 'Devis de référence',
            Publish: 'Publier',
            'Choose format': 'Choisir le format',
            'Choose layout': 'Choisir la mise en page',
            'Export columns': 'Exporter les colonnes',
            'Visible columns': 'Colonnes visibles',
            'All columns': 'Toutes les colonnes',
            Export: 'Exporter',
            'Go to account settings': 'Accéder aux paramètres du compte',
            'Open reports': 'Ouvrir les rapports',
            'Change color scheme': 'Modifier la couleur du schèma',
            'Change language': 'Modifier la langue',
            'Leave application...': 'Quitter l\'application...',
            'Filter navigation...': 'Filtrer la navigation...',
            Contracts: 'Contrats',
            Preview: 'Aperçu',
            'Add note': 'Ajouter une note',
            Notes: 'Notes',
            Class: 'Classe',
            Content: 'Contenu',
            Url: 'Url',
            'added a': 'a ajouté',
            'note on': 'une note sur',
            Attachements: 'Pièces jointes',
            'Document type': 'Type de document',
            'Is document obsolete': 'Le document est-il obsolète?',
            Description: 'Description',
            Choose: 'Choisir',
            'Upload file': 'Télécharger un fichier',
            Save: 'Sauvegarder'
        }
    };
}


